#!/bin/bash

# Update package list and install required packages
echo "Updating package list and installing necessary packages of qemu-kvm virt-manager..."
sudo apt update -y
sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager -y

echo "Finished."

