#!/bin/bash
echo;
echo "-----------------------------------------------------------------------------------------------------------------------";
echo "Start and restarting virt-manager services... (libvirtd.socket, libvirtd-admin.socket, libvirtd-ro.socket, libvirtd) "
echo "-----------------------------------------------------------------------------------------------------------------------";
echo;
sudo systemctl start libvirtd.socket;
sudo systemctl start libvirtd-admin.socket;
sudo systemctl start libvirtd-ro.socket;
sudo systemctl start libvirtd;
sudo systemctl restart libvirtd.socket;
sudo systemctl restart libvirtd-admin.socket;
sudo systemctl restart libvirtd-ro.socket;
sudo systemctl restart libvirtd;
echo;

echo "-----------------------------------------------------------------------------------------------------------------------";
echo "Status virt-manager"
echo "-----------------------------------------------------------------------------------------------------------------------";
sudo systemctl status libvirtd.socket;
sudo systemctl status libvirtd-admin.socket;
sudo systemctl status libvirtd-ro.socket;
sudo systemctl status libvirtd;

echo;
echo "-------------------------------";
echo "List of all Virtual Machines"
echo "-------------------------------";
echo;
sudo virsh list --all;
echo;
echo "-------------------------------";
echo "List of all Networks"
echo "-------------------------------";
echo;
sudo virsh net-list;
echo;


